version: '3.1'

services:

  db:
    image: postgres
    restart: always
    volumes:
      - ./docker/postgres-database.sh:/docker-entrypoint-initdb.d/postgres-database.sh
    ports:
      - "5435:5432"
    environment:
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=root
      - POSTGRES_MULTIPLE_DATABASES=study_blog