springdoc:
 api-docs:
   path: /api-docs
spring:
  h2:
    console:
    enabled: true
    path: /h2
  datasource:
    url: jdbc:h2:mem:blog
    username: admin
    password: admin
    driver-class-name: org.h2.Driver
    database-platform: org.hibernate.dialect.H2Dialect.jpa
    hibernate:
    ddl-auto: create
  output:
    ansi:
      enabled: ALWAYS